### ISSUE TITLE
Feat: add help-button to each data source

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#1358]
**I'm submitting a ...**  
[x] feature request

**...about**   
[x] admin experience UI
[x] Content Types or data management

**Current behavior**
no context-help on the data sources

**Expected behavior**
wish to provide more help on the DS

**Please tell us about your environment:**
* **2sxc version(s):** 9.7

**Todo**
* [x] provide help-info from data (eav-server)
* [x] show help-button in gui on mouse-over
* [x] create help pages or redirect on 2sxc or wiki
