### ISSUE TITLE
Enable automatic Polymorphism on views

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#2054]
**I'm submitting a ...** 
[x] feature request

**...about**   
[x] Polymorphism

**Current behavior**
To automatically switch templates in views from bs3 to bs4, or from staging to live it always requires a few lines of code in the template. It would be nicer if this were automated. 

**Todo**
* [x] develop the system / API
* [x] surface in the UI so it can easily be configured
* [x] document in docs
* [x] make sure code-editor is aware of the edition we're editing / looking at

**Please tell us about your environment:**

* **2sxc version(s):** 10.29
