### ISSUE TITLE
Oqtane: Update App-information to include required Oqtane version

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#2401]
**I'm submitting a ...**   
[x] feature request

**...about**   
[x] App-Export-Import
[x] Oqtane

**Todo**

* [x] Update Content-Type
* [ ] Ensure it's in the XML export
* [ ] Check it upon import

* **2sxc version(s):** 11.20
