### ISSUE TITLE
Enable View-Configuration to specify code for Search-Indexing work

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#2435]
**I'm submitting a ...**   
[x] feature request

**...about**   
[x] admin experience UI
[x] Razor templating
[x] Content Types or data management

**Current behavior**   

Currently there is a fairly hidden mechanism to override default search-indexing behavior. We want to make it more discoverable and place the code outside of the Razor-File. 

**Todo**

* [x] Implement configuration
* [x] Implement code changes on the IView object to get the data from configuration
* [x] Update search code to compile it etc. @tvatavuk 
* [x] Auto-generate a good sample search file @tvatavuk 
* [x] Document @iJungleboy 

**Your environment**  

* **2sxc version(s):** 12.01 and all before
