### ISSUE TITLE
Epic: V13 Release - Metadata, Visual Query, ...

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#2611]
# 2sxc V13 Release

This is a high level overview of tasks & status of the overall work. It should help the core developers keep everything in sight.

### Core changes

* [x] Deprecate some old APIs #2618 #2621 
* [x] Create log-warnings when code uses to-be-deprecated APIs
* [x] Move Site Settings to new App: Create a new site-level App automatically @tvatavuk 
* [x] Change code to use that App for site-level settings
* [x] #2625
* [ ] See how we can also integrate site-level metadata for use in page/ etc.

### Metadata

* [x] Backend: Add Metadata accessors to all CmsContext objects ✅ Site ✅ Page ✅ Module ✅ User @iJungleboy 
* [x] Backend: Enable anything with `IHasMetadata` to identify targets for better toolbars
* [x] Razor/Toolbar: Create simple API to create Metadata Buttons quickly and easily @iJungleboy #2597
* [x] Edit UI Backend: Provide more target information to Edit UI @iJungleboy 
* [x] Edit UI Front-End: Show that we're creating metadata @PagnoDunadan 
* [x] Edit UI Front-End: Show if something is Metadata and what for @PagnoDunadan 
* [x] Metadata: Create Decorators concept @iJungleboy 
* [x] Decorator: ✅ Save Empty Content-Type and ✅ UI should save types with Save-Empty @iJungleboy @PagnoDunadan 
* [x] UI: Manage Metadata dialog: ✅ Create ✅ Show Is-Metadata-For @PagnoDunadan 
* [x] Backend: Mark recommended _MetadataFor_ on Types and _MetadataExpected_ on Types - should work for: App, Content-Type, Entity, Attributes @iJungleboy 
* [x] Backend: Provide recommendations to Manage-Metadata dialog for App, Content-Type, Entity, Attributes @iJungleboy 
* [x] UI: Manage Metadata dialog: Recommendations @PagnoDunadan 
* [x] UI: Entity-List - improve metadata button to show is/has metadata: ✅ Heart ✅ Toggle ☑️ Count @PagnoDunadan 
* [x] UI: Content-Type List ☑️ MD-Button in table ☑️ with Count
* [x] UI: Attributes ☑️ MD-Button in List or Menu with Count
* [x] UI: App Settings ✅ MD Button ☑️ with Count
* [x] Decorators: Add Delete-Warning to config @iJungleboy 
* [x] UI: When deleting, show message on delete-warning @PagnoDunadan 
* [x] Target Types - Create target types for Custom @iJungleboy @tvatavuk 
* [x] Razor APIs - ensure that `App.Data.GetMetadata(...)` is available @iJungleboy 
* [x] Razor APIs - ensure that `App.Data.GetCustomMetadata(...)` is available @iJungleboy 

### .net 4.7.2 / .net Standard 2 Compliance

* [x] PoC working on Dnn 9 and Dnn 7 @tvatavuk 
* [x] Update Dependency Injection to .net standard 2 @tvatavuk 
* [x] Update Entity Framework to .net Standard 2 @tvatavuk 
* [x] During Installation: Clean Dnn Assemblies table from old values
* [x] During Installation: Rename the ToSic.SexyContent Dll to ToSic.Sxc.Dnn
* [x] Rename the ToSic.Dnn.Dnn9 to ToSic.Dnn.StartUp
* [x] ATM we still have too many DLLs which seem unnecessary; clean these - we should not need many new DLLs

### Visual Query

* [x] UI: Better Rename Stream dialog #2583 @PagnoDunadan 
* [x] DataSources: New Children and Parents data sources #2581 @iJungleboy 
* [x] DataSources: New MetadataOf and MetadataFor Data Sources #2586 @iJungleboy 
* [x] Show details for DS under each Query @PagnoDunadan 
* [x] Backend: Simple API to get all DS Details in one call @tvatavuk 
* [x] Ensure new quick-Api call is used at start (but not when just a single setting changes) @PagnoDunadan 

### Code Editor

* [x] Implement Monaco @PagnoDunadan 
* [x] Multi-Tab Editing @PagnoDunadan 
* [x] Show preview of new file @PagnoDunadan 
* [x] Improve Backend to load/save preferring path @tvatavuk 
* Maybe Improve backend to deliver Content-Types if a view-file is loaded from edit-UI across editions (difficult)

### Database and Infrastructure Changes

* [x] Change DI Overrides to use new Dnn 9 Startup where possible @tvatavuk 
* [x] Update tests to work again with latest DI @tvatavuk 
* [x] Try to use existing DependencyProvider on View
* [x] Disable previous method to override services - make it do nothing @iJungleboy 
* [x] Create DI based Factory for Dnn - update interface from the old implementation @iJungleboy 
* [x] Update examples for overriding Page Workflow @tvatavuk 
* [x] Maybe create guide how to use DI in Dnn on Modules and Skins @iJungleboy 

### Scope

* [x] #2623
* [x] UI: Verify UI handles the scope `Default` correctly (remove workarounds)

### App Sharing

* [x] Refactor providing global types as inheritance of App @iJungleboy 
* [x] Refactor marking shared types using ContentType-Decorator @iJungleboy 
* [x] Refactor marking shared entities using Entity-Decorator @iJungleboy 

### Edit UI

* [x] improve string/number dropdowns with Text-Entry to show better toggle switcher @PagnoDunadan 
* [x] Mark obsolete input-types using new Metadata Decorator @iJungleboy 
* [x] Mark common/recommended input-types in UI @iJungleboy 

### Image Resizer with WebP support for Dnn (Oqtane already has it)

* [x] PoC working on Dnn 7 and 9 @tvatavuk 
* [x] Installation and automatic handling of previously-installed Image-Resizer @tvatavuk 
* [x] Update to use .net 4.7.2 and Dnn 9 StartUp

### JS API

* [x] deprecate sxc.data with the old API and document @iJungleboy 
* [x] Create new route `app/[name]/data` to replace the `app/[name]/content` which was confusing #2622
* [x] Create a sxc.data service with ✅ get 1 ✅ get all ✅ create ✅ update ✅ create metadata ☑️ verify @PagnoDunadan 
* [x] Create a sxc.query service with ☑️ get all  @iJungleboy 
* [x] Backend: Implement data-create can process `for` to create metadata @tvatavuk 

### Architecture

* [x] Move Primary App from Content to another App which is dedicated to site-wide settings & metadata
