### ISSUE TITLE
Epic: Share App Definition Across Sites

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#2636]
**I'm submitting a ...**   
[x] feature request / epic

**...about**   
[x] admin experience UI
[x] shared data / apps across sites

**Current behavior**   

An App is created on a site. There are ways to share specific content-types across apps, but it's manual and complex, + data isn't shared. 

**Expected behavior**   

Goal is to create Master Apps, which can be inherited by other sites and thereby share all the main definitions of the master app. 

**Steps ca.**

* [x] Ensure Apps can inherit Apps
* [x] Get Content-Types to inherit, while still allowing data to be created in the target app
* [x] Ensure inherited content-types are not editable in the target app
* [x] Get data to inherit - possibly with exact specs
* [x] Make feature to allow this
* [x] Ensure inherited data cannot be edited
* [x] Get Settings / Resources to inherit
* [x] Make it configurable / discoverable
* [x] document

**Your environment**  

* **2sxc version(s):** 13
