### ISSUE TITLE
Epic: Fully Optimized / Automatic Image Resizing / Picture-Tag Generation

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#2639]
**I'm submitting a ...**   
[x] feature request

**...about**   
[x] Razor templating
[x] Responsive Images / HTML

**Current behavior**   

It's really hard to create perfect `<picture>` tags and `<img>` tags with best-possible `srcset`. This should be as automatic as possible, but still allow it's parts to be used separately, in case only a partial automation is expected. 

**Todo**

* [x] Improve `Link.Image` to also support generating `srcset` values #2638 
* [x] Store data what image formats can be resized and to what
* [x] Create an IImageService to get the format information
* [x] IImageService generates source-tags
* [x] IImageService generates entire picture tag
* [x] Create feature to generate picture tags for better / modern formats like WebP

**Your environment**  

* **2sxc version(s):** 13.00
