### ISSUE TITLE
Epic: Permissions to edit language

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#2642]
**I'm submitting a ...**   
[x] feature request

**...about**   
[x] edit experience / UI

**Current behavior**   

Once a user has edit permissions, he can edit all languages. Goal is to allow configuration so certain users can only edit certain languages. 

**Steps**

* [x] Create Metadata TargetType @iJungleboy 
* [x] Create basic UI to manage this in App Management @PagnoDunadan 
* [x] Create backend to read this and provide it to the Edit UI @iJungleboy 
* [x] Also check primary/site-app if the local app doesn't set these permissions @iJungleboy 
* [x] Make sure the metadata is always stored lower-case using the NameId @PagnoDunadan 
* [x] Implement blocks in the edit-UI to prevent editing other languages @PagnoDunadan 
* [x] Make it an optional, activatable feature @iJungleboy 
* [x] Disable toolbar from appearing in such scenarios
* [ ] Document @iJungleboy 

**Your environment**  

* **2sxc version(s):** 13.00
