### ISSUE TITLE
Epic: Edit Global App-Files

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#2659]
* [x] Get editor to show both global and local app files
* [x] Enable create global files on app-editor
* [x] Standardize terms to use "Shared" instead of global
* [x] Enable global app-storage in Oqtane @tvatavuk
