### ISSUE TITLE
Feature Request: Configuration Defaults and Overrides and System, Portal, App; maybe User, Group Level

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#919]
Basic discussion started in #847 but that discussion drifted off. So here's the summary

It would be desirable to configure some features at various levels. 
### Examples of settings
1. The default WYSIWYG could be remapped from TinyMCE to another one
2. The TinyMCE could be re-configured (if this was possible - pending feature) at an app or portal level to maybe show different buttons -> _note that this could also be done just by re-configuring the default wysiwyg to a custom tinyMCE which was added to this specific system_
3. ADAM could be disabled at a global level
4. Quick-Add (in the dnn-page) could be disabled at a global level
5. Some tinymce buttons could be disabled/enabled at a user-level
### Most likely scopes / range of setting-effect
1. System level (all portals)
2. Portal level
3. App-level - which would also survive export/import of the app
4. User-level - but it's unclear which setting would have precedent - portal or user
   1. User specific level (user ID 27)
   2. User-Group level (group "Registered Users") - yet unclear which group / combination would have precedent...
### Types of setting-overrides

If we look at any kind of setting, we will probably have the following kinds of overrides:
1. Use value "x" as default, if it is not configured (note that this will not be needed much)
2. Use value "x" as override, no matter what is configured (this is probably the most common case
3. Ignore all previous overrides - and use the system default (like to prevent override-propagation in an app, without having to turn off system-defaults)
### Places where a setting could be applied
1. All field-input-configuration properties, like all "Amount of lines in a multi-line text field" or 
2. DNN-Page toolbar level - like "disable the app-button in the toolbar"
3. DNN-Page effects - like "disable/enable quick-insert"
4. Default-input-Field-Type remapping - so "string-wysiwyg-default" would be replaced with "string-wysiwyg-tinymce"
### Further considerations
1. Note that the default override could change from language to language
2. Note that the settings would have certain type issues (text, boolean, etc.)
3. Note that some settings would certainly be multi-line (like a JSON for configuring the TinyMCE)
4. The "address" to target a setting could be an issue, because some settings will override a value in a field-configuration (like "all links shouldn't show adam") - needing to address "configuration:hyperlink-default>field:enableadam" while others like "in-page-scripts>enable-quick-insert" would have a very different target-address schema
5. when a configuration has an effect, it may be very hard to find out why the UI doesn't behave as expected, since you may never realize that there are overrides in place
### Possible solutions for this
1. A global config in a JSON or the DB, which only the host can manage, but has these effects  
   not really nice, as it wouldn't export/import at app-level, and you would always need host permissions even to configure a portal/app
2. many different JSONs in various folders - possible and fairly transparent, but would require a lot of code to retrieve and merge these
3. settings-entities which could be created at various scopes (system, portal, app, ...) - my currently favored solution
### Tasks to solve this issue
- [ ] ensure we have the full scope of the problem
- [ ] decide on which things to prioritize - I believe that system/portal/app-level would be good to persue, while user/group or fancy applications like "all fields beginning with Ti*" wouldn't be a good idea
- [ ] decide on how to implement - see suggestions below
- [ ] implement generic system for storing the settings
- [ ] implement generic system for retrieving the currently valid setting - both for server code as well as JS code
- [ ] implement that this setting is respected at the various level (like the edit-ui-fields, the dnn-page, etc. --> this would probably only be done on an as-needed-basis

Amount of work necessary: conceptual 0.5 to 1.0d, then the basic generic solution probably ca. 2-4d, and specific cases (like dnn-page-quick...) each ca. 0.25-0.5d (2-4h).

**Comment by iJungleboy** [comment]
close for now till we find a sponsor
